### ISSUE TITLE
can you give a json that i can use you plugins

### ISSUE THREAD

**Issue by Rigaln** [yomishino/FFXIVActionEffectRange#1]
can you give a json that i can use you plugins

**Comment by bladehawkz** [comment]
https://raw.githubusercontent.com/yomishino/MyDalamudPlugins/main/plugins.json
Here is his plugin json.

**Comment by yomishino** [comment]
> https://raw.githubusercontent.com/yomishino/MyDalamudPlugins/main/plugins.json Here is his plugin json. @yomishino You probably need an edit on your readme for this plugin (and maybe others) since it points to the wrong repo.

Oops! Thanks for point out that for me.
