### ISSUE TITLE
api9 update?

### ISSUE THREAD

**Issue by Theletha** [yomishino/FFXIVActionEffectRange#14]
will you update it for api9 ?

**Comment by yomishino** [comment]
Sorry for the delay. I have not been active on the game for a while...

Updated the plugin just now but only as a testing build. I am not sure how well it works as I don't have an active subscription to the game. I can only test it with a trial account.

**Comment by Theletha** [comment]
> Sorry for the delay. I have not been active on the game for a while...
> 
> Updated the plugin just now but only as a testing build. I am not sure how well it works as I don't have an active subscription to the game. I can only test it with a trial account.
> 
> If you nonetheless want to give it a try, please feel free to let me know if it still works or if there is any bug.

how do i use the new version? do i have to built it myself in visual studio? since it still says its out of date in dalamud ingame

**Comment by Theletha** [comment]
![image](https://github.com/yomishino/FFXIVActionEffectRange/assets/10131942/c6227041-665a-4ec7-88a5-ea774bf81459)

**Comment by Theletha** [comment]
i built it and added it to dev plugin and it is so far working great!

**Comment by yomishino** [comment]
> i built it and added it to dev plugin and it is so far working great!

Glad it works.

Just a side note that you should also be able to find it in the Dalamud plugin list, or receive the available update, if you enable "Get plugin testing builds" in Dalamud Settings (under the "Experimental" tab), though you will also receive testing builds of other plugins. So you will need to be careful especially if you also enabled plugin auto-update.

Building it directly from source code is certainly another option.

**Comment by Theletha** [comment]
i see! so thats why, thanks for the info!
