### ISSUE TITLE
Currently non-functional

### ISSUE THREAD

**Issue by SashaFFXIV** [yomishino/FFXIVActionEffectRange#2]
Activated plugin but cannot see anything being drawn when using actions. I tried adjusting settings, being in and out of combat, in and out of duties, ect, but nothing.

**Comment by yomishino** [comment]
I can't tell without further details as it works fine for me. Could you perhaps tell me some more about the actions you used and the settings?

Just for note, only AoE actions will be drawn, and some settings may prevent certain actions from being drawn even if the plugin itself is enabled.

**Comment by SashaFFXIV** [comment]
![image](https://user-images.githubusercontent.com/55117631/153120025-85c306e6-a69f-4790-a558-ce5ebd6e6a35.png)

These are the settings. I was using random AoE skills like Prognosis, Overpower, Mythril Tempest ect.

**Comment by yomishino** [comment]
It will draw the outline of the AoE circle/cone etc for these skills under the same setting here. So not likely any problem with the configuration itself.

If you are somewhat comfortable with Dalamud's debug dev log though, I added an option to have the plugin output some debug log. You can find it at the end in the configuration window after updating the plugin to v1.0.1.0.
This may help a bit although I'm not sure about it right now. Seems we might have some weird issue.

For the log thing, once you enable the logging option in the plugin setting, use the `/xllog` text command to open the debug log window and click the gear icon to set Log Level to Debug. 
Then you can use some AoE skills and copy all the logs generated by the plugin (you may want to filter the logs by clicking the magnifier icon and enter "ActionEffectRange" and checking "Enabled" to filter out logs generated by other plugins).

(Also, if you do decide to do the logging, I recommend looking for a place without other players or NPCs nearby to reduce unrelated logs.)

**Comment by SashaFFXIV** [comment]
I finally managed to get things to work. I'm not 100% sure what happened exactly but I think it was a conflict with another plugin somehow. I disabled and re-enabled this plugin and a bunch of others and it's now working just fine. I can give you my plugin list if you think that might help, but beyond that I'm not sure what happened.
