### ISSUE TITLE
All visual cues are just floating in the air

### ISSUE THREAD

**Issue by DuckOfDuckness** [yomishino/FFXIVActionEffectRange#8]
All dungeons, all raids, all jobs, all skills, etc. The visual cue is just always floating somewhere off to the left and up, and seem to move slightly with the camera.
I play in 4K and use GShade. Not sure what else might affect it.
I absolutely loved this plugin when it was working for me. Any info I can give for you to troubleshoot just ask.

**Comment by yomishino** [comment]
A similar issue appears in another plugin of mine (AetherCompass) and turning off dynamic resolution seems to help (See https://github.com/yomishino/FFXIVAetherCompass/issues/14#issuecomment-1295913637), so you might want to try it as a work-around for now.
I'll try to find some time to work on the issue, hopefully soon...

**Comment by DuckOfDuckness** [comment]
Ok yeah I'd completely forgotten about dynamic resolution. I turned it off as you suggested and everything works now. Thank you!

**Comment by yomishino** [comment]
Closed for now because the issue does not seem reproducible. Please feel free to reopen the issue if it happens again.
